project_name: ps-singer-tap
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
before:
  hooks:
    - go mod tidy
builds:
  - id: ps-singer-tap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/singer-tap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    binary: "ps-singer-tap"
  - id: ps-http-tap
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/http-tap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    binary: "ps-http-tap"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
nfpms:
  - maintainer: PlanetScale
    description: The PlanetScale Singer.io Tap
    homepage: https://github.com/planetscale/singer-tap
    license: Apache 2.0
    formats:
      - deb
      - rpm
    file_name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else }}{{ .Os }}{{ end }}_{{ .Arch }}
brews:
  - homepage: "https://planetscale.com/"
    description: "The PlanetScale Singer.io Tap"
    name: "ps-singer-tap"
    license: Apache 2.0
    tap:
      owner: planetscale
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "ps-singer-tap"
  - name: ps-http-tap
    homepage: "https://planetscale.com/"
    description: "Singer.io HTTP Tap"
    license: Apache 2.0
    tap:
      owner: planetscale
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "ps-http-tap"