project_name: ps-singer-tap
release:
  prerelease: auto # don't publish release with -rc1,-pre, etc suffixes
before:
  hooks:
    - go mod tidy
builds:
  - id: darwin-amd64
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    main: ./cmd/singer-tap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    binary: "ps-singer-tap"
  - id: darwin-arm64
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=0
    main: ./cmd/singer-tap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    binary: "ps-singer-tap"
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    main: ./cmd/singer-tap/main.go
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}
    flags:
      - -trimpath
    binary: "ps-singer-tap"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
