# syntax=docker/dockerfile:1

ARG GO_VERSION=1.21.5
FROM pscale.dev/wolfi-prod/go:${GO_VERSION} AS build

RUN apk add --no-cache ruby3.2-bundler && \
    gem install license_finder

WORKDIR /singer-tap
COPY . .
ENTRYPOINT []
RUN go mod download
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" ./cmd/singer-tap
