# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      context: .
    volumes:
      - .:/work
    working_dir: /work
    command: spec
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/singer-tap
    working_dir: /singer-tap

  licensing:
    build:
      context: containers/licensing
    volumes:
      - .:/work
    working_dir: /work
